from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COURSE = ROOT / "src" / "content" / "courses"
SLUG = "bioprocess-engineering/chapter-10-mass-transfer-basics.md"
IMG = "/images/courses/bioprocess-engineering/chapter-10"


def eq(expr, num=""):
    return (
        '<div class="equation-block">\n'
        f'  <span class="equation-main">{expr}</span>\n'
        f'  <span class="equation-number">{num}</span>\n'
        "</div>"
    )


def fig(name, alt, caption):
    return f"![{alt}]({IMG}/{name})\n*{caption}*"


FORMULAS = [
    ("M = dm/dτ", "(10.1)"),
    ("q = M/F = dm/(F dτ)", "(10.2)"),
    ("q<sub>V</sub> = M/V = dm/(V dτ)", "(10.3)"),
    ("q<sub>V</sub> = dC/dτ = qf", "(10.4)"),
    ("q = -D dC/dn", "(10.5)"),
    ("D = wl", "(10.6)"),
    ("D = [4.35 · 10<sup>-4</sup>T<sup>3/2</sup> / p(V<sub>A</sub><sup>1/3</sup> + V<sub>B</sub><sup>1/3</sup>)<sup>2</sup>] √(1/M<sub>A</sub> + 1/M<sub>B</sub>)", "(10.7)"),
    ("D = D<sub>0</sub>(p<sub>0</sub>/p)(T/T<sub>0</sub>)<sup>3/2</sup>", "(10.8)"),
    ("D = D<sub>0</sub>(T/T<sub>0</sub>)", "(10.9)"),
    ("D = D<sub>0</sub>(T/T<sub>0</sub>)<sup>2</sup>", "(10.10)"),
    ("q = Cw", "(10.11)"),
    ("q = q<sub>D</sub> + q<sub>c</sub>", "(10.12)"),
    ("q = -D<sub>cp</sub> dC/dn", "(10.13)"),
    ("D<sub>t</sub> = w′l", "(10.14)"),
    ("q = -D dC/dn", "(10.15)"),
    ("q = βΔC", "(10.16)"),
    ("M = β(C - C<sub>p</sub>)F", "(10.17)"),
    ("β = D/δ", "(10.18)"),
    ("β = 2√(D/(πτ))", "(10.19)"),
    ("β = 2√(D<sub>e</sub>/(πτ))", "(10.20)"),
    ("β = √(DS)", "(10.21)"),
    ("q = KΔC", "(10.22)"),
    ("q = β<sub>g</sub>(C<sub>g</sub> - C<sub>p</sub>)", "(10.23)"),
    ("q = β<sub>l</sub>(C<sub>p</sub> - C<sub>l</sub>)", "(10.24)"),
    ("q = β<sub>l</sub>(C<sub>p</sub> - C*)/m", "(10.25)"),
    ("q = K<sub>g</sub>ΔC<sub>g</sub> = (C<sub>g</sub> - C*)/(1/β<sub>g</sub> + m/β<sub>l</sub>)", "(10.26)"),
    ("q = K<sub>l</sub>ΔC<sub>l</sub> = (C* - C<sub>l</sub>)/(1/β<sub>l</sub> + 1/(mβ<sub>g</sub>))", "(10.27)"),
    ("M = ∫ qF = ∫ KΔC F", "(10.28)"),
    ("M = ∫ q<sub>V</sub>V = ∫ K<sub>V</sub>ΔC V", "(10.29)"),
    ("M = (Kf)SHΔC", "(10.30)"),
    ("ΔC<sub>m</sub> = (ΔC<sub>p</sub> - ΔC<sub>k</sub>)/ln(ΔC<sub>p</sub>/ΔC<sub>k</sub>)", "(10.31)"),
    ("M = G(C<sub>p</sub> - C<sub>k</sub>)", "(10.32)"),
    ("H = G(C<sub>p</sub> - C<sub>k</sub>)/(KfSΔC<sub>m</sub>) = hn", "(10.33)"),
    ("n = ∫ dC/(C - C*)", "(10.34)"),
    ("Nu′ = βl/D", "(10.35)"),
    ("Pr′ = ν/D", "(10.36)"),
    ("Nu′ = ARe<sup>m</sup>Pr′<sup>n</sup>", "(10.37)"),
    ("β = D<sub>d</sub>/δ<sub>d</sub>", "(10.38)"),
    ("Bi = βl/D<sub>d</sub>", "(10.39)"),
    ("Fo = Dτ/l<sup>2</sup>", "(10.40)"),
    ("τ = l<sup>2</sup>/D<sub>d</sub>", "(10.41)"),
    ("Pe′ = wl/D", "(10.42)"),
    ("q = -D(∂C/∂n + K<sub>t</sub>/T · ∂T/∂n + K<sub>b</sub>/p · ∂p/∂n)", "(10.43)"),
]


TEXT = {
    "uk": {
        "start": "## Матеріал підручника",
        "end": "## Після опрацювання розділу студент має вміти",
        "title": "## Матеріал підручника",
        "body": [
            "Матеріал відповідає логіці розділу 10 підручника Зав'ялова: спочатку вводяться масообмінні процеси, далі розглядаються молекулярна і конвективна дифузія, масовіддача, масопередача, критерії подібності та термодифузія.",
            "### 10.1. Загальні відомості",
            "Масообмінними, або дифузійними, називають процеси перерозподілу маси між фазами та всередині фаз, зумовлені прагненням системи до фізико-хімічної рівноваги. Рушійною силою є різниця між фактичною концентрацією компонента в даній фазі та його рівноважною концентрацією.",
            "До масообмінних процесів належать абсорбція, ректифікація, сушіння, адсорбція, десорбція, іонний обмін, екстрагування, кристалізація, розчинення та рідинна екстракція. У біотехнологічних і харчових виробництвах вони потрібні для очищення, концентрування, виділення цільових компонентів і підготовки продуктів до зберігання.",
            "Під час розрахунку аналізують три блоки: фазову рівновагу, робочі умови за матеріальними балансами і кінетику перенесення маси. Кінетика пов'язана з конструкцією апарата, бо саме гідродинамічний режим визначає реальну швидкість перенесення.",
            eq(FORMULAS[0][0], FORMULAS[0][1]),
            "Питомий потік маси відносять до поверхні масопередачі або до робочого об'єму апарата:",
            eq(FORMULAS[1][0], FORMULAS[1][1]),
            eq(FORMULAS[2][0], FORMULAS[2][1]),
            eq(FORMULAS[3][0], FORMULAS[3][1]),
            "де C - концентрація цільового компонента, кг/м3; f = F/V - питома поверхня масопередачі. У реальному апараті M, q, qV, C і f є середніми величинами, бо дисипація енергії та активна поверхня розподілені нерівномірно.",
            "### 10.2. Молекулярна дифузія",
            "Молекулярна дифузія є перенесенням речовини внаслідок хаотичного теплового руху молекул у напрямку з меншою концентрацією. Навколо джерела речовини виникає поле концентрацій та ізоконцентраційні поверхні; найбільша зміна концентрації спостерігається за нормаллю до такої поверхні.",
            fig("fig-10-1.webp", "До визначення градієнта концентрацій", "Рис. 10.1. До визначення градієнта концентрацій"),
            "Перший закон Фіка для усталеної молекулярної дифузії:",
            eq(FORMULAS[4][0], FORMULAS[4][1]),
            "Коефіцієнт молекулярної дифузії D залежить від властивостей речовин, температури, тиску і концентрації. Для газів його часто оцінюють за молекулярно-кінетичними залежностями:",
            eq(FORMULAS[5][0], FORMULAS[5][1]),
            eq(FORMULAS[6][0], FORMULAS[6][1]),
            "Для перерахунку табличних значень коефіцієнта дифузії на інші умови використовують температурно-тискові поправки:",
            eq(FORMULAS[7][0], FORMULAS[7][1]),
            eq(FORMULAS[8][0], FORMULAS[8][1]),
            eq(FORMULAS[9][0], FORMULAS[9][1]),
            "### 10.3. Конвективна дифузія",
            "У рухомому середовищі речовина переноситься не лише молекулами, а й разом із потоком. Конвективна дифузія поєднує молекулярний механізм із макроперенесенням середовищем.",
            eq(FORMULAS[10][0], FORMULAS[10][1]),
            eq(FORMULAS[11][0], FORMULAS[11][1]),
            "Сумарний процес часто описують через ефективний коефіцієнт дифузії:",
            eq(FORMULAS[12][0], FORMULAS[12][1]),
            eq(FORMULAS[13][0], FORMULAS[13][1]),
            "### 10.4. Масопередача",
            "Масовіддача описує перенесення компонента від ядра однієї фази до межі поділу фаз або від межі поділу в ядро іншої фази. Для тонкої примежової плівки потік визначають за законом Фіка:",
            eq(FORMULAS[14][0], FORMULAS[14][1]),
            "У технічних розрахунках застосовують коефіцієнт масовіддачі β:",
            eq(FORMULAS[15][0], FORMULAS[15][1]),
            eq(FORMULAS[16][0], FORMULAS[16][1]),
            fig("fig-10-2.webp", "Примежові плівки біля межі поділу фаз", "Рис. 10.2. Схема примежових плівок біля межі поділу фаз"),
            eq(FORMULAS[17][0], FORMULAS[17][1]),
            fig("fig-10-3.webp", "Структура турбулентного потоку", "Рис. 10.3. Структура турбулентного потоку: 1 - основний потік; 2 - примежовий підшар; 3 - в'язкий підшар; 4 - дифузійний підшар; 5 - тверда фаза"),
            "Плівкова теорія спрощує реальну картину, але пояснює роль примежового шару. Теорія оновлення поверхні пов'язує масовіддачу з часом контакту елементів поверхні, а теорія проникнення враховує нестаціонарність перенесення.",
            eq(FORMULAS[18][0], FORMULAS[18][1]),
            eq(FORMULAS[19][0], FORMULAS[19][1]),
            eq(FORMULAS[20][0], FORMULAS[20][1]),
            "Масопередача між двома фазами записується через загальний коефіцієнт K і загальну рушійну силу:",
            eq(FORMULAS[21][0], FORMULAS[21][1]),
            eq(FORMULAS[22][0], FORMULAS[22][1]),
            eq(FORMULAS[23][0], FORMULAS[23][1]),
            eq(FORMULAS[24][0], FORMULAS[24][1]),
            eq(FORMULAS[25][0], FORMULAS[25][1]),
            eq(FORMULAS[26][0], FORMULAS[26][1]),
            "Для апаратних розрахунків потік інтегрують по поверхні або по об'єму контакту фаз:",
            eq(FORMULAS[27][0], FORMULAS[27][1]),
            eq(FORMULAS[28][0], FORMULAS[28][1]),
            eq(FORMULAS[29][0], FORMULAS[29][1]),
            eq(FORMULAS[30][0], FORMULAS[30][1]),
            eq(FORMULAS[31][0], FORMULAS[31][1]),
            eq(FORMULAS[32][0], FORMULAS[32][1]),
            eq(FORMULAS[33][0], FORMULAS[33][1]),
            "### 10.5. Подібність дифузійних процесів",
            "Подібність дифузійних процесів дає змогу переносити результати дослідів і моделей на промислові апарати. Основні критерії враховують масовіддачу, молекулярну дифузію, в'язкість і швидкість потоку.",
            eq(FORMULAS[34][0], FORMULAS[34][1]),
            eq(FORMULAS[35][0], FORMULAS[35][1]),
            eq(FORMULAS[36][0], FORMULAS[36][1]),
            eq(FORMULAS[37][0], FORMULAS[37][1]),
            eq(FORMULAS[38][0], FORMULAS[38][1]),
            eq(FORMULAS[39][0], FORMULAS[39][1]),
            eq(FORMULAS[40][0], FORMULAS[40][1]),
            eq(FORMULAS[41][0], FORMULAS[41][1]),
            "Зв'язок Pe′ = RePr′ показує, що конвективне перенесення визначається одночасно гідродинамікою потоку та дифузійними властивостями системи.",
            "### 10.6. Поняття про термодифузію",
            "Термодифузія виникає тоді, коли на перенесення речовини, крім градієнта концентрації, впливають градієнти температури і тиску. У біотехнологічних апаратах це важливо для зон нагрівання, охолодження, стерилізації та концентрування.",
            eq(FORMULAS[42][0], FORMULAS[42][1]),
        ],
    },
    "en": {
        "start": "## Lecture Notes",
        "end": "## After studying this chapter, students should be able to",
        "title": "## Lecture Notes",
        "body": [
            "This lecture follows Chapter 10 of Zavialov's textbook: mass-transfer processes are introduced first, then molecular and convective diffusion, mass-transfer coefficients, overall mass transfer, similarity criteria and thermodiffusion.",
            "### 10.1. General Information",
            "Mass-transfer, or diffusion, processes redistribute mass between phases and within phases as the system tends toward physicochemical equilibrium. The driving force is the difference between the actual concentration of a component in a phase and its equilibrium concentration.",
            "Absorption, rectification, drying, adsorption, desorption, ion exchange, extraction, crystallization, dissolution and liquid extraction are typical mass-transfer processes. In biotechnology and food production they are used to purify, concentrate, isolate target components and prepare products for storage.",
            "Engineering analysis considers phase equilibrium, operating conditions from material balances, and transfer kinetics. Kinetics is tied to equipment design because the hydrodynamic regime controls the real transfer rate.",
            eq(FORMULAS[0][0], FORMULAS[0][1]),
            "The specific mass flux can be referred to the transfer surface or to the working volume:",
            *[eq(a, b) for a, b in FORMULAS[1:4]],
            "where C is the concentration of the target component and f = F/V is the specific mass-transfer surface.",
            "### 10.2. Molecular Diffusion",
            "Molecular diffusion is the transfer of matter caused by random thermal motion of molecules toward lower concentration. Around a source of substance, a concentration field and isoconcentration surfaces are formed.",
            fig("fig-10-1.webp", "Defining the concentration gradient", "Fig. 10.1. Defining the concentration gradient"),
            "Fick's first law for steady molecular diffusion is:",
            eq(FORMULAS[4][0], FORMULAS[4][1]),
            "The molecular diffusion coefficient depends on substance properties, temperature, pressure and concentration. For gases it is often estimated from molecular-kinetic relations:",
            *[eq(a, b) for a, b in FORMULAS[5:10]],
            "### 10.3. Convective Diffusion",
            "In a moving medium, a component is carried both by molecules and by the bulk flow. Convective diffusion combines molecular transfer with macroscopic transport by the medium.",
            *[eq(a, b) for a, b in FORMULAS[10:14]],
            "### 10.4. Mass Transfer",
            "Mass transfer near an interface is commonly described through a boundary film and the mass-transfer coefficient β.",
            *[eq(a, b) for a, b in FORMULAS[14:17]],
            fig("fig-10-2.webp", "Boundary films at the phase interface", "Fig. 10.2. Boundary-film scheme at the phase interface"),
            eq(FORMULAS[17][0], FORMULAS[17][1]),
            fig("fig-10-3.webp", "Turbulent-flow structure", "Fig. 10.3. Turbulent-flow structure: 1 - main flow; 2 - boundary sublayer; 3 - viscous sublayer; 4 - diffusion sublayer; 5 - solid phase"),
            "Film theory, surface-renewal theory and penetration theory explain why turbulence, contact time and the condition of the interfacial layer determine the mass-transfer coefficient.",
            *[eq(a, b) for a, b in FORMULAS[18:34]],
            "### 10.5. Similarity of Diffusion Processes",
            "Similarity criteria make it possible to transfer experimental or model results to industrial apparatuses. The key criteria include mass transfer, molecular diffusion, viscosity and flow velocity.",
            *[eq(a, b) for a, b in FORMULAS[34:42]],
            "The relation Pe′ = RePr′ shows that convective transfer is governed by both flow hydrodynamics and diffusion properties.",
            "### 10.6. Concept of Thermodiffusion",
            "Thermodiffusion occurs when temperature and pressure gradients influence mass transfer along with the concentration gradient. This is important in heating, cooling, sterilization and concentration zones of biotechnological equipment.",
            eq(FORMULAS[42][0], FORMULAS[42][1]),
        ],
    },
    "de": {
        "start": "## Vorlesungsskript",
        "end": "## Nach dem Durcharbeiten dieses Kapitels sollen Studierende",
        "title": "## Vorlesungsskript",
        "body": [
            "Diese Vorlesung folgt Kapitel 10 des Lehrbuchs von Zavialov: zuerst werden Stoffuebergangsprozesse eingefuehrt, danach molekulare und konvektive Diffusion, Stoffuebergangskoeffizienten, Stoffuebertragung, Aehnlichkeitskriterien und Thermodiffusion.",
            "### 10.1. Allgemeines",
            "Stoffuebergangs- oder Diffusionsprozesse verteilen Masse zwischen Phasen und innerhalb von Phasen um, wenn ein System zum physikalisch-chemischen Gleichgewicht strebt. Die Triebkraft ist die Differenz zwischen tatsaechlicher und Gleichgewichtskonzentration.",
            "Zu diesen Prozessen gehoeren Absorption, Rektifikation, Trocknung, Adsorption, Desorption, Ionenaustausch, Extraktion, Kristallisation, Loesen und Fluessigextraktion. In biotechnologischen und lebensmitteltechnologischen Produktionen dienen sie der Reinigung, Konzentrierung und Abtrennung von Zielkomponenten.",
            "Die technische Analyse betrachtet Phasengleichgewicht, Betriebsbedingungen aus Stoffbilanzen und die Kinetik der Uebertragung.",
            eq(FORMULAS[0][0], FORMULAS[0][1]),
            "Der spezifische Stoffstrom wird auf die Uebertragungsflaeche oder auf das Arbeitsvolumen bezogen:",
            *[eq(a, b) for a, b in FORMULAS[1:4]],
            "Dabei ist C die Konzentration der Zielkomponente und f = F/V die spezifische Stoffuebertragungsflaeche.",
            "### 10.2. Molekulare Diffusion",
            "Molekulare Diffusion ist der Stofftransport infolge der zufaelligen Waermebewegung der Molekuele in Richtung geringerer Konzentration.",
            fig("fig-10-1.webp", "Bestimmung des Konzentrationsgradienten", "Abb. 10.1. Zur Bestimmung des Konzentrationsgradienten"),
            "Das erste Fick'sche Gesetz fuer stationaere molekulare Diffusion lautet:",
            eq(FORMULAS[4][0], FORMULAS[4][1]),
            "Der Diffusionskoeffizient haengt von Stoffeigenschaften, Temperatur, Druck und Konzentration ab.",
            *[eq(a, b) for a, b in FORMULAS[5:10]],
            "### 10.3. Konvektive Diffusion",
            "In einem bewegten Medium wird ein Stoff sowohl durch Molekuele als auch mit der Hauptstroemung transportiert.",
            *[eq(a, b) for a, b in FORMULAS[10:14]],
            "### 10.4. Stoffuebertragung",
            "Der Stoffuebergang an der Phasengrenze wird haeufig durch einen Grenzfilm und den Stoffuebergangskoeffizienten β beschrieben.",
            *[eq(a, b) for a, b in FORMULAS[14:17]],
            fig("fig-10-2.webp", "Grenzfilme an der Phasengrenze", "Abb. 10.2. Schema der Grenzfilme an der Phasengrenze"),
            eq(FORMULAS[17][0], FORMULAS[17][1]),
            fig("fig-10-3.webp", "Struktur einer turbulenten Stroemung", "Abb. 10.3. Struktur einer turbulenten Stroemung: 1 - Hauptstroemung; 2 - Grenzunterschicht; 3 - viskose Unterschicht; 4 - Diffusionsunterschicht; 5 - feste Phase"),
            "Filmtheorie, Oberflaechenerneuerung und Eindringtheorie zeigen, warum Turbulenz, Kontaktzeit und Zustand der Grenzschicht den Stoffuebergangskoeffizienten bestimmen.",
            *[eq(a, b) for a, b in FORMULAS[18:34]],
            "### 10.5. Aehnlichkeit von Diffusionsprozessen",
            "Aehnlichkeitskriterien erlauben die Uebertragung von Modell- und Versuchsdaten auf Industrieapparate.",
            *[eq(a, b) for a, b in FORMULAS[34:42]],
            "Pe′ = RePr′ verbindet konvektiven Stofftransport mit Hydrodynamik und Diffusionseigenschaften.",
            "### 10.6. Begriff der Thermodiffusion",
            "Thermodiffusion entsteht, wenn neben dem Konzentrationsgradienten auch Temperatur- und Druckgradienten den Stofftransport beeinflussen.",
            eq(FORMULAS[42][0], FORMULAS[42][1]),
        ],
    },
    "ru": {
        "start": "## Конспект лекции",
        "end": "## После изучения раздела студент должен уметь",
        "title": "## Конспект лекции",
        "body": [
            "Материал следует логике раздела 10 учебника Завьялова: сначала вводятся массообменные процессы, затем рассматриваются молекулярная и конвективная диффузия, массоотдача, массопередача, критерии подобия и термодиффузия.",
            "### 10.1. Общие сведения",
            "Массообменными, или диффузионными, называют процессы перераспределения массы между фазами и внутри фаз, обусловленные стремлением системы к физико-химическому равновесию. Движущая сила - разность между фактической концентрацией компонента и его равновесной концентрацией.",
            "К массообменным процессам относят абсорбцию, ректификацию, сушку, адсорбцию, десорбцию, ионный обмен, экстрагирование, кристаллизацию, растворение и жидкостную экстракцию. В биотехнологических и пищевых производствах они нужны для очистки, концентрирования и выделения целевых компонентов.",
            "При расчете анализируют фазовое равновесие, рабочие условия по материальным балансам и кинетику переноса массы.",
            eq(FORMULAS[0][0], FORMULAS[0][1]),
            "Удельный поток массы относят к поверхности массопередачи или к рабочему объему аппарата:",
            *[eq(a, b) for a, b in FORMULAS[1:4]],
            "где C - концентрация целевого компонента; f = F/V - удельная поверхность массопередачи.",
            "### 10.2. Молекулярная диффузия",
            "Молекулярная диффузия - перенос вещества вследствие хаотического теплового движения молекул в направлении меньшей концентрации.",
            fig("fig-10-1.webp", "К определению градиента концентраций", "Рис. 10.1. К определению градиента концентраций"),
            "Первый закон Фика для установившейся молекулярной диффузии:",
            eq(FORMULAS[4][0], FORMULAS[4][1]),
            "Коэффициент молекулярной диффузии зависит от свойств веществ, температуры, давления и концентрации.",
            *[eq(a, b) for a, b in FORMULAS[5:10]],
            "### 10.3. Конвективная диффузия",
            "В движущейся среде вещество переносится не только молекулами, но и вместе с потоком.",
            *[eq(a, b) for a, b in FORMULAS[10:14]],
            "### 10.4. Массопередача",
            "Массоотдачу около границы фаз часто описывают через пограничную пленку и коэффициент массоотдачи β.",
            *[eq(a, b) for a, b in FORMULAS[14:17]],
            fig("fig-10-2.webp", "Пограничные пленки у границы раздела фаз", "Рис. 10.2. Схема пограничных пленок у границы раздела фаз"),
            eq(FORMULAS[17][0], FORMULAS[17][1]),
            fig("fig-10-3.webp", "Структура турбулентного потока", "Рис. 10.3. Структура турбулентного потока: 1 - основной поток; 2 - пограничный подслой; 3 - вязкий подслой; 4 - диффузионный подслой; 5 - твердая фаза"),
            "Пленочная теория, теория обновления поверхности и теория проникновения объясняют, почему турбулентность, время контакта и состояние межфазного слоя определяют коэффициент массоотдачи.",
            *[eq(a, b) for a, b in FORMULAS[18:34]],
            "### 10.5. Подобие диффузионных процессов",
            "Критерии подобия позволяют переносить данные опытов и моделей на промышленные аппараты.",
            *[eq(a, b) for a, b in FORMULAS[34:42]],
            "Связь Pe′ = RePr′ показывает, что конвективный перенос определяется гидродинамикой потока и диффузионными свойствами системы.",
            "### 10.6. Понятие о термодиффузии",
            "Термодиффузия возникает, когда на перенос вещества, кроме градиента концентрации, влияют градиенты температуры и давления.",
            eq(FORMULAS[42][0], FORMULAS[42][1]),
        ],
    },
}


def replace_between(text, start, end, replacement):
    start_i = text.index(start)
    end_i = text.index(end)
    return text[:start_i] + replacement.rstrip() + "\n\n" + text[end_i:]


for locale, data in TEXT.items():
    path = COURSE / locale / SLUG
    original = path.read_text(encoding="utf-8")
    body = data["title"] + "\n\n" + "\n\n".join(data["body"])
    path.write_text(replace_between(original, data["start"], data["end"], body), encoding="utf-8")
    print(f"updated {path}")
